-- create tables
create table requiredcourses (
    id                             number generated by default on null as identity 
                                   constraint requiredcourses_id_pk primary key,
    sequence                       number(2) not null,
    coursename                     varchar2(100 char) not null,
    coursenumber                   varchar2(25 char) not null,
    sectionnumber                  varchar2(25 char),
    classnumber                    varchar2(25 char),
    startdate                      date,
    completiondate                 date,
    finalgradeletter               varchar2(2 char),
    finalgradenumber               number(4,3),
    creditsearned                  number(4)
)
;

create table weeklyassignments (
    id                             number generated by default on null as identity 
                                   constraint weeklyassignments_id_pk primary key,
    course                         number
                                   constraint weeklyassignments_course_fk
                                   references requiredcourses on delete cascade not null,
    week                           number(2),
    assignmenttype                 varchar2(100 char),
    assignmentname                 varchar2(100 char),
    turnindate                     date,
    isturnedin                     varchar2(3 char),
    grade                          number(5,2)
)
;

-- table index
create index weeklyassignments_i1 on weeklyassignments (course);

-- load data
 
-- Generated by Quick SQL Monday February 21, 2022  19:15:06
 
/*
REQUIREDCOURSES  
    sequence num(2) /nn
    courseName vc(100) /nn
    courseNumber vc(25) /nn
    sectionNumber vc(25)
    classNumber  vc(25)
    startDate
    completionDate
    finalGradeLetter vc(2)
    finalGradeNumber num(4,3)
    creditsEarned num(4)

WEEKLYASSIGNMENTS  
    course/fk REQUIREDCOURSES /nn
    week num(2)
    assignmentType vc(100)
    assignmentName vc(100)
    turnInDate
    isTurnedIn vc(3)
    grade num(5,2)

# settings = { PK: "IDENTITY", semantics: "CHAR", language: "EN", APEX: true }
*/
